# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mood_tracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mood_tracker

  target 'mood_tracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mood_trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

end
